{
	"_id": "65872d75d061f19e4e4a0a55",
	"minDuration": 345600,
	"maxDuration": 345600,
	"maxLimitDuration": 604800,
	"minDate": null,
	"maxDate": null,
	"maxLimitDate": null,
	"displayRemainingTime": false,
	"limitLockTime": true,
	"maxLockedUsers": 3,
	"isPublic": false,
	"requireContact": true,
	"name": "🟧 The Foundry: Assimilation ⬛⬛",
	"password": "IWantToBeADrone",
	"description": "The Foundry is looking for Drone Candidates.Here you will become a pup drone. Your assimilation will be guided by The Foundry's central AI. Join and become One. Kinks: Dronification, identity loss, humiliation Gear needed: dildo, butt plug, chastity cagePassword:IWantToBeADroneNotes:Responses to the bot are always start with \"TRANSACTION: #\". Bot will give response examples to each task. Bot will have a deliberate delay from the completion of one task to the next.What will happen is you'll get a message that is a task and you'll have to complete it. The bot checks in every half hour and delays between tasks to start the next on. You'll get your first message within 30 min of joining.",
	"unsplashPhoto": {
		"id": "Sj_3Jdr19L4",
		"name": "Alek Kalinowski",
		"url": "https://images.unsplash.com/flagged/photo-1595524288414-a7fda0a12d0c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMzE4NDZ8MHwxfGFsbHx8fHx8fHx8fDE3MDMzNTc4MTN8&ixlib=rb-4.0.3&q=80&w=1080",
		"username": "alekversusworld"
	},
	"hideTimeLogs": true,
	"lastSavedAt": "2024-01-03T19:13:59.683Z",
	"requirePassword": true,
	"user": {
		"_id": "64e5b481b533a5ccfe61567f",
		"username": "PupHimbo",
		"isPremium": false,
		"description": "Pup looking for more friends, cuddles, and cum, and maybe a cage. Aspiring to be a slutty Himbo pup",
		"location": "San Francisco ",
		"gender": "Male",
		"age": 27,
		"role": "switch",
		"isFindom": false,
		"avatarUrl": "https://cdn01.chaster.app/app/uploads/avatars/EfcMg0h1HiLUc67j.jpg",
		"online": false,
		"lastSeen": null,
		"isAdmin": false,
		"isModerator": false,
		"metadata": {
			"locktober2020Points": 0,
			"locktober2021Points": 0,
			"chastityMonth2022Points": 0,
			"locktober2022Points": 0,
			"locktober2023Points": 1240
		},
		"fullLocation": "San Francisco , California, United States",
		"discordId": "1153172669559214141",
		"discordUsername": "puphimbo",
		"isDisabled": false,
		"isSuspended": false,
		"features": [],
		"joinedAt": "2023-08",
		"isNewMember": false,
		"isSuspendedOrDisabled": false
	},
	"durationMode": "duration",
	"isFindom": false,
	"calculatedMaxLimitDuration": 604800,
	"extensions": []
}